# Generated by Django 5.2.8 on 2025-12-17 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_viewhistory_favoritedestination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewhistory',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='viewhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='FavoriteDestination',
        ),
        migrations.DeleteModel(
            name='ViewHistory',
        ),
    ]
