# Generated by Django 5.2.8 on 2025-12-08 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên địa điểm')),
                ('travel_type', models.CharField(max_length=50, verbose_name='Loại hình du lịch')),
                ('location', models.CharField(max_length=100, verbose_name='Vị trí')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ chi tiết')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('image', models.ImageField(blank=True, upload_to='destinations/')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Kinh độ')),
                ('avg_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Giá trung bình (VNĐ)')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Địa điểm',
                'verbose_name_plural': 'Địa điểm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='Từ khóa tìm kiếm')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('results_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lịch sử tìm kiếm',
                'verbose_name_plural': 'Lịch sử tìm kiếm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0.0, verbose_name='Điểm tổng thể (0-100)')),
                ('review_score', models.FloatField(default=0.0, verbose_name='Điểm từ đánh giá')),
                ('sentiment_score', models.FloatField(default=0.0, verbose_name='Điểm cảm xúc')),
                ('popularity_score', models.FloatField(default=0.0, verbose_name='Điểm phổ biến')),
                ('total_reviews', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(default=0.0)),
                ('positive_review_ratio', models.FloatField(default=0.0, verbose_name='Tỷ lệ đánh giá tích cực')),
                ('last_calculated', models.DateTimeField(auto_now=True, verbose_name='Lần tính cuối')),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='travel.destination')),
            ],
            options={
                'verbose_name': 'Điểm gợi ý',
                'verbose_name_plural': 'Điểm gợi ý',
                'ordering': ['-overall_score'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Tên người đánh giá')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Đánh giá (1-5 sao)')),
                ('comment', models.TextField(verbose_name='Nội dung đánh giá')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sentiment_score', models.FloatField(default=0.0, verbose_name='Điểm cảm xúc (-1 đến 1)')),
                ('positive_keywords', models.JSONField(blank=True, default=list, verbose_name='Từ khóa tích cực')),
                ('negative_keywords', models.JSONField(blank=True, default=list, verbose_name='Từ khóa tiêu cực')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='travel.destination')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Đánh giá',
                'ordering': ['-created_at'],
            },
        ),
    ]
