# Generated by Django 5.2.8 on 2025-12-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['location'], name='idx_dest_location'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['travel_type'], name='idx_dest_type'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['created_at'], name='idx_dest_created'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['location', 'travel_type'], name='idx_dest_loc_type'),
        ),
        migrations.AddIndex(
            model_name='recommendationscore',
            index=models.Index(fields=['-overall_score'], name='idx_rec_score'),
        ),
        migrations.AddIndex(
            model_name='recommendationscore',
            index=models.Index(fields=['-avg_rating'], name='idx_rec_rating'),
        ),
        migrations.AddIndex(
            model_name='recommendationscore',
            index=models.Index(fields=['-total_reviews'], name='idx_rec_reviews'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['destination', '-created_at'], name='idx_review_dest_date'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='idx_review_created'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='idx_review_rating'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['-created_at'], name='idx_search_created'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['query'], name='idx_search_query'),
        ),
    ]
