# Generated by Django 5.2.8 on 2025-12-17 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_add_database_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Ten danh muc')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug URL')),
                ('description', models.TextField(blank=True, verbose_name='Mo ta')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon class')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Danh muc',
                'verbose_name_plural': 'Danh muc',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chu thich')),
                ('order', models.IntegerField(default=0, verbose_name='Thu tu hien thi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Anh dia diem',
                'verbose_name_plural': 'Anh dia diem',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ten tour')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('details', models.TextField(verbose_name='Chi tiet tour')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Gia (VND)')),
                ('duration', models.IntegerField(help_text='So ngay', verbose_name='Thoi luong')),
                ('address_detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dia chi don/tra khach')),
                ('image_main', models.ImageField(blank=True, null=True, upload_to='packages/main_images/', verbose_name='Anh chinh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Dang hoat dong')),
                ('is_available_today', models.BooleanField(default=False, help_text='Tour kha dung trong ngay hien tai', verbose_name='Co san hom nay')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngay bat dau')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngay ket thuc')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Goi tour',
                'verbose_name_plural': 'Goi tour',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dia diem', 'verbose_name_plural': 'Dia diem'},
        ),
        migrations.AlterModelOptions(
            name='recommendationscore',
            options={'ordering': ['-overall_score'], 'verbose_name': 'Diem goi y', 'verbose_name_plural': 'Diem goi y'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Danh gia', 'verbose_name_plural': 'Danh gia'},
        ),
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lich su tim kiem', 'verbose_name_plural': 'Lich su tim kiem'},
        ),
        migrations.AddField(
            model_name='destination',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Dia diem noi bat'),
        ),
        migrations.AddField(
            model_name='destination',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Danh gia trung binh'),
        ),
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Slug URL'),
        ),
        migrations.AddField(
            model_name='destination',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dia chi chi tiet'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='avg_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Gia trung binh (VND)'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mo ta'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Vi do'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Vi tri'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Kinh do'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Ten dia diem'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='travel_type',
            field=models.CharField(max_length=50, verbose_name='Loai hinh du lich'),
        ),
        migrations.AlterField(
            model_name='recommendationscore',
            name='last_calculated',
            field=models.DateTimeField(auto_now=True, verbose_name='Lan tinh cuoi'),
        ),
        migrations.AlterField(
            model_name='recommendationscore',
            name='overall_score',
            field=models.FloatField(default=0.0, verbose_name='Diem tong the (0-100)'),
        ),
        migrations.AlterField(
            model_name='recommendationscore',
            name='popularity_score',
            field=models.FloatField(default=0.0, verbose_name='Diem pho bien'),
        ),
        migrations.AlterField(
            model_name='recommendationscore',
            name='positive_review_ratio',
            field=models.FloatField(default=0.0, verbose_name='Ty le danh gia tich cuc'),
        ),
        migrations.AlterField(
            model_name='recommendationscore',
            name='review_score',
            field=models.FloatField(default=0.0, verbose_name='Diem tu danh gia'),
        ),
        migrations.AlterField(
            model_name='recommendationscore',
            name='sentiment_score',
            field=models.FloatField(default=0.0, verbose_name='Diem cam xuc'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author_name',
            field=models.CharField(max_length=100, verbose_name='Ten nguoi danh gia'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(verbose_name='Noi dung danh gia'),
        ),
        migrations.AlterField(
            model_name='review',
            name='negative_keywords',
            field=models.JSONField(blank=True, default=list, verbose_name='Tu khoa tieu cuc'),
        ),
        migrations.AlterField(
            model_name='review',
            name='positive_keywords',
            field=models.JSONField(blank=True, default=list, verbose_name='Tu khoa tich cuc'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Danh gia (1-5 sao)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='sentiment_score',
            field=models.FloatField(default=0.0, verbose_name='Diem cam xuc (-1 den 1)'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='query',
            field=models.CharField(max_length=255, verbose_name='Tu khoa tim kiem'),
        ),
        migrations.AddField(
            model_name='destination',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations', to='travel.category', verbose_name='Danh muc'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['rating'], name='idx_dest_rating'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['is_popular'], name='idx_dest_popular'),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travel.destination'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_packages', to='travel.category', verbose_name='Danh muc'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='travel.destination', verbose_name='Dia diem'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['is_active'], name='idx_tour_active'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['price'], name='idx_tour_price'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['start_date', 'end_date'], name='idx_tour_dates'),
        ),
    ]
