# Generated by Django 5.2.7 on 2025-11-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/images/'),
        ),
    ]
