# Generated by Django 5.2.7 on 2025-11-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/images/'),
        ),
    ]
