# Generated by Django 5.2.8 on 2025-12-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_tourimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='rating',
            new_name='score',
        ),
    ]
