# Generated by Django 5.2.8 on 2025-12-17 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_category_destinationimage_tourpackage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL, verbose_name='Nguoi dung'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user'], name='idx_search_user'),
        ),
    ]
