# Generated by Django 5.2.7 on 2025-11-24 03:09

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('travel', '0004_remove_destinationimage_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_packages', to='travel.category'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='image_main',
            field=models.ImageField(blank=True, null=True, upload_to='packages/main_images/'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
