# Generated by Django 5.2.8 on 2025-12-18 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_add_user_to_searchhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_ip', models.GenericIPAddressField()),
                ('reason', models.CharField(choices=[('spam', 'Spam/Quảng cáo'), ('inappropriate', 'Nội dung không phù hợp'), ('fake', 'Đánh giá giả'), ('other', 'Lý do khác')], max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Báo cáo đánh giá',
                'verbose_name_plural': 'Báo cáo đánh giá',
            },
        ),
        migrations.CreateModel(
            name='ReviewVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('vote_type', models.CharField(choices=[('helpful', 'Hữu ích'), ('not_helpful', 'Không hữu ích')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vote đánh giá',
                'verbose_name_plural': 'Vote đánh giá',
            },
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đánh giá', 'verbose_name_plural': 'Đánh giá'},
        ),
        migrations.AddField(
            model_name='review',
            name='helpful_count',
            field=models.IntegerField(default=0, verbose_name='Số lượt hữu ích'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Đã xác minh'),
        ),
        migrations.AddField(
            model_name='review',
            name='not_helpful_count',
            field=models.IntegerField(default=0, verbose_name='Số lượt không hữu ích'),
        ),
        migrations.AddField(
            model_name='review',
            name='report_count',
            field=models.IntegerField(default=0, verbose_name='Số lượt báo cáo'),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='approved', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddField(
            model_name='review',
            name='travel_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Loại chuyến đi'),
        ),
        migrations.AddField(
            model_name='review',
            name='travel_with',
            field=models.CharField(blank=True, max_length=50, verbose_name='Đi cùng ai'),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AddField(
            model_name='review',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, verbose_name='User Agent'),
        ),
        migrations.AddField(
            model_name='review',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP người dùng'),
        ),
        migrations.AddField(
            model_name='review',
            name='visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày đi'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author_name',
            field=models.CharField(max_length=100, verbose_name='Tên người đánh giá'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(verbose_name='Nội dung đánh giá'),
        ),
        migrations.AlterField(
            model_name='review',
            name='negative_keywords',
            field=models.JSONField(blank=True, default=list, verbose_name='Từ khóa tiêu cực'),
        ),
        migrations.AlterField(
            model_name='review',
            name='positive_keywords',
            field=models.JSONField(blank=True, default=list, verbose_name='Từ khóa tích cực'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Đánh giá (1-5 sao)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='sentiment_score',
            field=models.FloatField(default=0.0, verbose_name='Điểm cảm xúc (-1 đến 1)'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['status'], name='idx_review_status'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='idx_review_user'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-helpful_count'], name='idx_review_helpful'),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='reporter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='travel.review'),
        ),
        migrations.AddField(
            model_name='reviewvote',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='travel.review'),
        ),
        migrations.AddField(
            model_name='reviewvote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reviewvote',
            unique_together={('review', 'user')},
        ),
    ]
