# Generated by Django 5.2.8 on 2025-12-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_rename_rating_destination_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
