# Generated by Django 5.2.7 on 2025-11-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_tourpackage_category_tourpackage_image_main_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourpackage',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='is_available_today',
            field=models.BooleanField(default=False, help_text='Check nếu tour này khả dụng trong ngày hiện tại hoặc tương lai gần.'),
        ),
    ]
