# Generated by Django 5.2.8 on 2025-12-27 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_tourpackage_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0.0, verbose_name='Diem tong the (0-100)')),
                ('review_score', models.FloatField(default=0.0, verbose_name='Diem tu danh gia')),
                ('sentiment_score', models.FloatField(default=0.0, verbose_name='Diem cam xuc')),
                ('popularity_score', models.FloatField(default=0.0, verbose_name='Diem pho bien')),
                ('total_reviews', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(default=0.0)),
                ('positive_review_ratio', models.FloatField(default=0.0, verbose_name='Ty le danh gia tich cuc')),
                ('last_calculated', models.DateTimeField(auto_now=True, verbose_name='Lan tinh cuoi')),
            ],
            options={
                'verbose_name': 'Diem goi y',
                'verbose_name_plural': 'Diem goi y',
                'ordering': ['-overall_score'],
            },
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_ip', models.GenericIPAddressField()),
                ('reason', models.CharField(choices=[('spam', 'Spam/Quảng cáo'), ('inappropriate', 'Nội dung không phù hợp'), ('fake', 'Đánh giá giả'), ('other', 'Lý do khác')], max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Báo cáo đánh giá',
                'verbose_name_plural': 'Báo cáo đánh giá',
            },
        ),
        migrations.CreateModel(
            name='ReviewVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('vote_type', models.CharField(choices=[('helpful', 'Hữu ích'), ('not_helpful', 'Không hữu ích')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='Tu khoa tim kiem')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('results_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lich su tim kiem',
                'verbose_name_plural': 'Lich su tim kiem',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đánh giá', 'verbose_name_plural': 'Đánh giá'},
        ),
        migrations.AddField(
            model_name='review',
            name='author_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.destination'),
        ),
        migrations.AddField(
            model_name='review',
            name='helpful_count',
            field=models.IntegerField(default=0, verbose_name='Số lượt hữu ích'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Đã xác minh'),
        ),
        migrations.AddField(
            model_name='review',
            name='negative_keywords',
            field=models.JSONField(blank=True, default=list, verbose_name='Từ khóa tiêu cực'),
        ),
        migrations.AddField(
            model_name='review',
            name='not_helpful_count',
            field=models.IntegerField(default=0, verbose_name='Số lượt không hữu ích'),
        ),
        migrations.AddField(
            model_name='review',
            name='positive_keywords',
            field=models.JSONField(blank=True, default=list, verbose_name='Từ khóa tích cực'),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Đánh giá (1-5 sao)'),
        ),
        migrations.AddField(
            model_name='review',
            name='report_count',
            field=models.IntegerField(default=0, verbose_name='Số lượt báo cáo'),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment_score',
            field=models.FloatField(default=0.0, verbose_name='Điểm cảm xúc (-1 đến 1)'),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='approved', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddField(
            model_name='review',
            name='travel_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Loại chuyến đi'),
        ),
        migrations.AddField(
            model_name='review',
            name='travel_with',
            field=models.CharField(blank=True, max_length=50, verbose_name='Đi cùng ai'),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, verbose_name='User Agent'),
        ),
        migrations.AddField(
            model_name='review',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP người dùng'),
        ),
        migrations.AddField(
            model_name='review',
            name='visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày đi'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['destination', '-created_at'], name='idx_review_dest_date'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='idx_review_created'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='idx_review_rating'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['status'], name='idx_review_status'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='idx_review_user'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-helpful_count'], name='idx_review_helpful'),
        ),
        migrations.AddField(
            model_name='recommendationscore',
            name='destination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='travel.destination'),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='reporter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='travel.review'),
        ),
        migrations.AddField(
            model_name='reviewvote',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='travel.review'),
        ),
        migrations.AddField(
            model_name='reviewvote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL, verbose_name='Nguoi dung'),
        ),
        migrations.AddIndex(
            model_name='recommendationscore',
            index=models.Index(fields=['-overall_score'], name='idx_rec_score'),
        ),
        migrations.AddIndex(
            model_name='recommendationscore',
            index=models.Index(fields=['-avg_rating'], name='idx_rec_rating'),
        ),
        migrations.AddIndex(
            model_name='recommendationscore',
            index=models.Index(fields=['-total_reviews'], name='idx_rec_reviews'),
        ),
        migrations.AddConstraint(
            model_name='reviewvote',
            constraint=models.UniqueConstraint(condition=models.Q(('user', None), _negated=True), fields=('review', 'user'), name='unique_user_vote'),
        ),
        migrations.AddConstraint(
            model_name='reviewvote',
            constraint=models.UniqueConstraint(condition=models.Q(('user_ip', None), _negated=True), fields=('review', 'user_ip'), name='unique_ip_vote'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['-created_at'], name='idx_search_created'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['query'], name='idx_search_query'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user'], name='idx_search_user'),
        ),
    ]
