# Generated by Django 5.2.8 on 2026-01-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_enhanced_review_ugc'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='aspect_scores',
            field=models.JSONField(blank=True, default=dict, verbose_name='Điểm theo khía cạnh'),
        ),
        migrations.AddField(
            model_name='review',
            name='sarcasm_risk',
            field=models.BooleanField(default=False, verbose_name='Nguy cơ mỉa mai'),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadata phân tích'),
        ),
    ]
