# Generated by Django 5.2.8 on 2026-01-02 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_enhanced_review_ugc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Danh mục', 'verbose_name_plural': 'Danh mục'},
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['-created_at'], 'verbose_name': 'Địa điểm', 'verbose_name_plural': 'Địa điểm'},
        ),
        migrations.AlterModelOptions(
            name='destinationimage',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Ảnh địa điểm', 'verbose_name_plural': 'Ảnh địa điểm'},
        ),
        migrations.AlterModelOptions(
            name='tourpackage',
            options={'ordering': ['name'], 'verbose_name': 'Gói tour', 'verbose_name_plural': 'Gói tour'},
        ),
        migrations.RemoveIndex(
            model_name='destination',
            name='idx_dest_location',
        ),
        migrations.RemoveIndex(
            model_name='destination',
            name='idx_dest_type',
        ),
        migrations.RemoveIndex(
            model_name='destination',
            name='idx_dest_created',
        ),
        migrations.RemoveIndex(
            model_name='destination',
            name='idx_dest_loc_type',
        ),
        migrations.RemoveIndex(
            model_name='destination',
            name='idx_dest_rating',
        ),
        migrations.RemoveIndex(
            model_name='destination',
            name='idx_dest_popular',
        ),
        migrations.RemoveIndex(
            model_name='tourpackage',
            name='idx_tour_active',
        ),
        migrations.RemoveIndex(
            model_name='tourpackage',
            name='idx_tour_price',
        ),
        migrations.RemoveIndex(
            model_name='tourpackage',
            name='idx_tour_dates',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='address_detail',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tên danh mục'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ chi tiết'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='avg_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá TB (VND)'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations', to='travel.category', verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Địa điểm nổi bật'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Vĩ độ'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Vị trí'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Kinh độ'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên địa điểm'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Đánh giá'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='travel_type',
            field=models.CharField(max_length=50, verbose_name='Loại hình du lịch'),
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chú thích'),
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Thứ tự hiển thị'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_packages', to='travel.category', verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='travel.destination', verbose_name='Địa điểm'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='details',
            field=models.TextField(verbose_name='Chi tiết tour'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='duration',
            field=models.IntegerField(help_text='Số ngày', verbose_name='Thời lượng'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='image_main',
            field=models.ImageField(blank=True, null=True, upload_to='packages/main_images/', verbose_name='Ảnh chính'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='is_available_today',
            field=models.BooleanField(default=False, verbose_name='Có sẵn hôm nay'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên tour'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá (VND)'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu'),
        ),
    ]
