# Generated by Django 5.2.8 on 2026-01-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_review_aspect_scores_review_sarcasm_risk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_low_quality',
            field=models.BooleanField(default=False, verbose_name='Chất lượng thấp'),
        ),
        migrations.AddField(
            model_name='review',
            name='spam_flags',
            field=models.JSONField(blank=True, default=list, verbose_name='Cờ spam'),
        ),
        migrations.AddField(
            model_name='review',
            name='spam_score',
            field=models.FloatField(default=0.0, verbose_name='Điểm spam (0-1)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('shadow', 'Shadow-ban')], default='approved', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
