# Generated by Django 5.2.8 on 2026-01-02 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_alter_category_options_alter_destination_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='average_rating',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_tours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='meeting_point',
            field=models.CharField(blank=True, help_text='Địa điểm tập trung cụ thể', max_length=255),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='start_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='start_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
