# Generated by Django 5.2.7 on 2025-11-24 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_alter_tourpackage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='address_detail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ đón/trả khách hoặc địa chỉ chính'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.category'),
        ),
    ]
