# Generated by Django 5.2.8 on 2026-01-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_accountprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
