# Generated by Django 5.2.8 on 2026-01-02 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_tourpackage_average_rating_tourpackage_favorites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationscore',
            name='destination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_stats', to='travel.destination'),
        ),
        migrations.CreateModel(
            name='DestinationRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.IntegerField(default=0)),
                ('total_favorites', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(default=0.0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='destination_stats', to='travel.destination')),
            ],
        ),
    ]
