# Generated by Django 5.2.8 on 2026-01-05 08:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('travel', '0008_alter_accountprofile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categories', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['-created_at'], 'verbose_name': 'Destination', 'verbose_name_plural': 'Destination'},
        ),
        migrations.AlterModelOptions(
            name='destinationimage',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Image', 'verbose_name_plural': 'Image'},
        ),
        migrations.RemoveIndex(
            model_name='recommendationscore',
            name='idx_rec_rating',
        ),
        migrations.RenameIndex(
            model_name='recommendationscore',
            new_name='travel_reco_overall_020cf9_idx',
            old_name='idx_rec_score',
        ),
        migrations.RenameIndex(
            model_name='recommendationscore',
            new_name='travel_reco_total_r_f52380_idx',
            old_name='idx_rec_reviews',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='score',
        ),
        migrations.RemoveField(
            model_name='recommendationscore',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='travel_type',
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='avg_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Gia trung binh (VND)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='destination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Vi do'),
        ),
        migrations.AddField(
            model_name='destination',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Kinh do'),
        ),
        migrations.AddField(
            model_name='destination',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Thu tu hien thi'),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recommendationscore',
            name='total_favorites',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommendationscore',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='travel.destination'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='details',
            field=models.TextField(verbose_name='Chi tiết tour'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['is_active'], name='travel_tour_is_acti_d32ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['price'], name='travel_tour_price_c1bb73_idx'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['start_date', 'end_date'], name='travel_tour_start_d_464924_idx'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='travel.destination'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='destination',
            name='travel_type',
            field=models.ManyToManyField(blank=True, related_name='destinations', to='travel.traveltype'),
        ),
        migrations.AddField(
            model_name='review',
            name='travel_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.traveltype', verbose_name='Loại chuyến đi'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['location'], name='travel_dest_locatio_f37beb_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['avg_rating'], name='travel_dest_avg_rat_83dba0_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['is_popular'], name='travel_dest_is_popu_faf135_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['created_at'], name='travel_dest_created_03e83b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'destination')},
        ),
    ]
