# Generated by Django 5.2.9 on 2025-12-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_auto_20251124_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='rating',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
