# Generated by Django 5.2.9 on 2025-12-02 16:26

from django.db import migrations
from django.utils.text import slugify

def populate_slug(apps, schema_editor):
    TourPackage = apps.get_model('travel', 'TourPackage')
    for package in TourPackage.objects.filter(slug__isnull=True):
        package.slug = slugify(package.name)
        package.save()



class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_remove_destination_rating_tourpackage_rating_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_slug),
    ]

