# Generated by Django 5.2.8 on 2025-11-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_alter_tourpackage_price_alter_tourpackage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
