# Generated by Django 6.0 on 2026-01-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_alter_category_options_category_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='tags',
        ),
        migrations.AddField(
            model_name='destination',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Tags'),
        ),
    ]
