# Generated by Django 6.0 on 2026-01-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_remove_destination_tags_destination_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='rating',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='average_rating',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='meeting_point',
            field=models.CharField(blank=True, help_text='Địa điểm tập trung cụ thể', max_length=255),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='start_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='start_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='tags',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Tags'),
        ),
    ]
