# Generated by Django 6.0 on 2026-01-06 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_remove_tourpackage_rating_tourpackage_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendationscore',
            options={'ordering': ['-overall_score'], 'verbose_name': 'Điểm gợi ý', 'verbose_name_plural': 'Điểm gợi ý'},
        ),
        migrations.RemoveIndex(
            model_name='recommendationscore',
            name='travel_reco_total_r_f52380_idx',
        ),
        migrations.AddField(
            model_name='recommendationscore',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recommendationscore',
            name='tour',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='travel.tourpackage'),
        ),
        migrations.AlterField(
            model_name='recommendationscore',
            name='destination',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='travel.destination'),
        ),
        migrations.AlterField(
            model_name='recommendationscore',
            name='last_calculated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recommendationscore',
            name='overall_score',
            field=models.FloatField(default=0.0, verbose_name='Điểm tổng thể (0-100)'),
        ),
        migrations.AlterField(
            model_name='recommendationscore',
            name='popularity_score',
            field=models.FloatField(default=0.0, verbose_name='Điểm phổ biến'),
        ),
        migrations.AlterField(
            model_name='recommendationscore',
            name='positive_review_ratio',
            field=models.FloatField(default=0.0, verbose_name='Tỷ lệ đánh giá tích cực'),
        ),
        migrations.AlterField(
            model_name='recommendationscore',
            name='sentiment_score',
            field=models.FloatField(default=0.0, verbose_name='Điểm cảm xúc'),
        ),
        migrations.RemoveField(
            model_name='recommendationscore',
            name='review_score',
        ),
        migrations.RemoveField(
            model_name='recommendationscore',
            name='total_favorites',
        ),
        migrations.RemoveField(
            model_name='recommendationscore',
            name='total_views',
        ),
    ]
