# Generated by Django 6.0 on 2026-01-06 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_alter_recommendationscore_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favorite',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='travel.tourpackage'),
        ),
        migrations.AddField(
            model_name='review',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='travel.tourpackage'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'destination', 'tour')},
        ),
    ]
