# Generated by Django 6.0 on 2026-01-07 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('travel', '0015_remove_review_tour_tourreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reviewvote',
            name='unique_user_vote',
        ),
        migrations.RemoveConstraint(
            model_name='reviewvote',
            name='unique_ip_vote',
        ),
        migrations.RemoveField(
            model_name='reviewreport',
            name='review',
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewvote',
            name='tour_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='travel.tourreview'),
        ),
        migrations.AddIndex(
            model_name='reviewreport',
            index=models.Index(fields=['content_type', 'object_id'], name='travel_revi_content_e9571e_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewvote',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('user', None), _negated=True), models.Q(('review', None), _negated=True)), fields=('review', 'user'), name='unique_user_vote'),
        ),
        migrations.AddConstraint(
            model_name='reviewvote',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('user', None), _negated=True), models.Q(('tour_review', None), _negated=True)), fields=('tour_review', 'user'), name='unique_user_tour_vote'),
        ),
    ]
