# Generated by Django 6.0 on 2026-01-07 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_remove_reviewvote_unique_user_vote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewvote',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='travel.review'),
        ),
    ]
