# Generated by Django 6.0 on 2026-01-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_alter_reviewvote_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourreview',
            name='is_verified_purchase',
            field=models.BooleanField(default=False, verbose_name='Khách hàng thực tế'),
        ),
        migrations.AddField(
            model_name='tourreview',
            name='is_verified_user',
            field=models.BooleanField(default=False, verbose_name='Tài khoản đã xác minh'),
        ),
        migrations.AddField(
            model_name='tourreview',
            name='not_helpful_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Không hữu ích'),
        ),
        migrations.AddField(
            model_name='tourreview',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('published', 'Đã hiển thị'), ('hidden', 'Đã ẩn (Vi phạm)')], default='published', max_length=10),
        ),
    ]
