# Generated by Django 6.0 on 2026-01-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_alter_favorite_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_review', models.FloatField(default=0.4, verbose_name='Trọng số: Điểm đánh giá (Rating)')),
                ('w_sentiment', models.FloatField(default=0.3, verbose_name='Trọng số: Cảm xúc AI')),
                ('w_popularity', models.FloatField(default=0.3, verbose_name='Trọng số: Độ phổ biến')),
                ('popularity_point_per_review', models.IntegerField(default=5, verbose_name='Điểm cộng cho mỗi Review')),
                ('min_interactions_for_recommend', models.IntegerField(default=5, verbose_name='Số tương tác tối thiểu để hiện Gợi ý')),
            ],
            options={
                'verbose_name': 'Cấu hình Thuật toán Gợi ý',
            },
        ),
    ]
