# Generated by Django 6.0 on 2026-01-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0020_recommendationconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendationconfig',
            options={'verbose_name': 'Công thức tính điểm'},
        ),
        migrations.RemoveField(
            model_name='recommendationconfig',
            name='w_popularity',
        ),
        migrations.RemoveField(
            model_name='recommendationconfig',
            name='w_review',
        ),
        migrations.RemoveField(
            model_name='recommendationconfig',
            name='w_sentiment',
        ),
        migrations.AddField(
            model_name='recommendationconfig',
            name='popularity_score',
            field=models.FloatField(default=0.3, verbose_name='Popularity score'),
        ),
        migrations.AddField(
            model_name='recommendationconfig',
            name='review_score',
            field=models.FloatField(default=0.4, verbose_name='Review score'),
        ),
        migrations.AddField(
            model_name='recommendationconfig',
            name='sentiment_score',
            field=models.FloatField(default=0.3, verbose_name='Sentiment score'),
        ),
    ]
