# Generated by Django 6.0 on 2026-01-20 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0020_favoritedestination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ tên người đặt')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(max_length=254)),
                ('departure_date', models.DateField(verbose_name='Ngày khởi hành')),
                ('number_of_adults', models.PositiveIntegerField(default=1, verbose_name='Số người lớn')),
                ('number_of_children', models.PositiveIntegerField(default=0, verbose_name='Số trẻ em')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='Yêu cầu đặc biệt')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='travel.tourpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
