# Generated by Django 6.0 on 2026-01-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0021_alter_recommendationconfig_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendationconfig',
            name='min_interactions_for_recommend',
        ),
        migrations.AlterField(
            model_name='recommendationconfig',
            name='popularity_point_per_review',
            field=models.IntegerField(default=5, verbose_name='Điểm cộng cho mỗi đánh giá'),
        ),
    ]
