# Generated by Django 6.0 on 2026-01-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0022_booking_booking_code_booking_payment_status'),
        ('travel', '0022_remove_recommendationconfig_min_interactions_for_recommend_and_more'),
    ]

    operations = [
    ]
