# Generated by Django 5.2.8 on 2026-01-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0023_merge_20260124_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourreview',
            name='negative_keywords',
            field=models.JSONField(blank=True, default=list, verbose_name='Từ khóa tiêu cực'),
        ),
        migrations.AddField(
            model_name='tourreview',
            name='positive_keywords',
            field=models.JSONField(blank=True, default=list, verbose_name='Từ khóa tích cực'),
        ),
        migrations.AddField(
            model_name='tourreview',
            name='sentiment_score',
            field=models.FloatField(default=0.0, verbose_name='Điểm cảm xúc (-1 đến 1)'),
        ),
        migrations.AlterField(
            model_name='tourreview',
            name='is_verified_purchase',
            field=models.BooleanField(default=False, verbose_name='Khách đã trải nghiệm tour'),
        ),
    ]
