# Generated by Django 6.0 on 2026-01-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0023_merge_20260123_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_ticket_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tourreview',
            name='is_verified_purchase',
            field=models.BooleanField(default=False, verbose_name='Khách đã trải nghiệm tour'),
        ),
    ]
