# Generated by Django 6.0 on 2026-01-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0023_merge_20260124_0205'),
        ('travel', '0024_booking_is_ticket_sent_and_more'),
    ]

    operations = [
    ]
