# Generated by Django 6.1.1 on 2026-10-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0025_alter_booking_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán'), ('refunded', 'Đã hoàn tiền')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='tourreview',
            name='not_helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
