# Generated by Django 6.1.1 on 2026-10-05 14:41

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0026_alter_booking_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá (1-5 sao)'),
        ),
        migrations.AlterField(
            model_name='tourreview',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Điểm (1-5)'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('tour__isnull', False)), fields=('user', 'tour'), name='uniq_favorite_user_tour'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False), ('destination__isnull', False)), fields=('destination', 'user'), name='uniq_review_destination_user'),
        ),
        migrations.AddConstraint(
            model_name='tourreview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('tour', 'user'), name='uniq_tourreview_tour_user'),
        ),
    ]
